# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad2b5f052a90153f89d8c342af45cd0e08f818165da4c69833da19d2146a9f8dac4d4d4b0852aecf1f78f676067740bc57c5819f585f0347b64fbfad41ec71fb

test:
  secret_key_base: 69ceaaf94d4e7e8989cde898f1b3a6bce7b1993b316b03be607ce394443cbd0050ecde1c6854f45815f24adb232238109f0d4af86900718c92182922ce2b15ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
